# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Demo Test Pipeline

on:  
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  Test:

    runs-on: macos-latest

    steps:
    - name: Get Sources
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip        
        pip install -r requirements.txt
    
    - name: Run Tests
      run: |
        nose2
    
    - name: Create Test Artifact
      if: always()      
      uses: actions/upload-artifact@v3
      with:
          name: my-artifact
          path: test_results/
